# Generated by Django 6.0 on 2025-12-22 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_role', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('REVIEW', 'Review Requested')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_person_name', models.CharField(blank=True, max_length=100)),
                ('pickup_person_phone', models.CharField(blank=True, max_length=15)),
                ('pickup_person_relation', models.CharField(blank=True, max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('outgoing_date', models.DateField()),
                ('outgoing_time', models.TimeField()),
                ('expected_return_date', models.DateField()),
                ('expected_return_time', models.TimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('mode_of_travel', models.CharField(blank=True, max_length=100)),
                ('is_priority', models.BooleanField(default=False)),
                ('priority_reason', models.TextField(blank=True)),
                ('priority_level', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CHECKED_OUT', 'Checked Out'), ('COMPLETED', 'Completed (Returned)'), ('EXPIRED', 'Expired'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=50)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('gate_number', models.CharField(blank=True, max_length=20)),
                ('meeting_scheduled', models.BooleanField(default=False)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True)),
                ('fee_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
