# Generated by Django 6.0 on 2025-12-22 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpasses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpass',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_outpasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpass',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_outpasses', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='outpass',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_outpasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outpass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpasses', to='students.student'),
        ),
        migrations.AddField(
            model_name='approval',
            name='outpass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='outpasses.outpass'),
        ),
        migrations.AddIndex(
            model_name='outpass',
            index=models.Index(fields=['status', 'is_priority'], name='outpasses_o_status_8c5129_idx'),
        ),
        migrations.AddIndex(
            model_name='outpass',
            index=models.Index(fields=['outgoing_date', 'expected_return_date'], name='outpasses_o_outgoin_f91624_idx'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('outpass', 'approver_role'), name='unique_outpass_approval_role'),
        ),
    ]
