# Generated by Django 6.0 on 2025-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpasses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='meeting_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FEE_PENDING', 'Fee Pending'), ('APPROVED', 'Approved'), ('READY_FOR_EXIT', 'Ready for Exit'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CHECKED_OUT', 'Checked Out'), ('COMPLETED', 'Completed (Returned)'), ('EXPIRED', 'Expired'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=50),
        ),
    ]
