# Generated by Django 6.0 on 2025-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpasses', '0003_outpass_meeting_venue_alter_outpass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='verification_photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FEE_PENDING', 'Fee Pending'), ('APPROVED', 'Approved'), ('READY_FOR_EXIT', 'Ready for Exit'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('MEETING', 'Meeting'), ('CHECKED_OUT', 'Checked Out'), ('COMPLETED', 'Completed (Returned)'), ('EXPIRED', 'Expired'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=50),
        ),
    ]
