# Generated by Django 6.0 on 2025-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpasses', '0004_outpass_verification_photo_alter_outpass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='exit_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='outpass',
            name='return_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
