# Generated by Django 6.0 on 2025-12-22 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('finance', '0001_initial'),
        ('outpasses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='outpass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fees', to='outpasses.outpass'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfee'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'fee_type', 'academic_year'), name='unique_student_fee'),
        ),
    ]
