# Generated by Django 6.0 on 2025-12-22 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('COED', 'Co-Ed')], max_length=10)),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField(default=2)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
