# Generated by Django 6.0 on 2025-12-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='contact_number',
        ),
    ]
