# Generated by Django 6.0 on 2025-12-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('housing', '0003_remove_hostel_address_remove_hostel_capacity_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('class_obj', 'section', 'roll_number'), name='unique_class_section_roll_no'),
        ),
    ]
